const ResponseCode = {
    INVALID_INPUT: "ERR_INVALID_INPUT",
    UNAUTHORIZED: "ERR_UNAUTHORIZED",
    FORBIDDEN: "ERR_FORBIDDEN",
    NOT_FOUND: "ERR_NOT_FOUND",
    INTERNAL_SERVER_ERROR: "ERR_INTERNAL_SERVER_ERROR",
    SUCCESS: "SUCCESS",
};

export default ResponseCode;
